# Book settings
title:
author: Development Data Group
logo: images/logo.png
only_build_toc_files: false

repository:
  url: https://github.com/worldbank/blackmarblepy
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/blackmarblepy
  html_favicon: "images/favicon.ico"

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
    apidoc_module_dir: "../src"
    extra_extensions:
      - "sphinx.ext.napoleon"
      - "sphinxcontrib.apidoc"
